kind: Kustomization

namespace: ${NAMESPACE}

configMapGenerator:
- name: chris-config
  env: secrets/.chris.env
- name: chris-db-config
  env: secrets/.chris_db.env
- name: chris-store-config
  env: secrets/.chris_store.env
- name: chris-store-db-config
  env: secrets/.chris_store_db.env
- name: pfcon-config
  env: secrets/.pfcon.env
- name: pman-config
  env: secrets/.pman.env
- name: swift-config
  env: secrets/.swift_service.env

resources:
- resources/chris.yaml
- resources/worker.yaml
- resources/worker-periodic.yaml
- resources/scheduler.yaml
- resources/chris-db.yaml
- resources/chris-store.yaml
- resources/chris-store-db.yaml
- resources/rabbitmq.yaml
- resources/swift.yaml
- resources/pfcon.yaml
- resources/pman.yaml
