kind: Kustomization

namespace: chris
commonLabels:
  env: production

configMapGenerator:
- name: chris-config
  envs:
  - ./secrets/.chris.env
  - ./secrets/.chris_db.env
  - ./secrets/.swift_service.env

resources:
- resources/chris.yaml
- resources/worker.yaml
- resources/worker-periodic.yaml
- resources/scheduler.yaml
- resources/chris-db.yaml
- resources/chris-store.yaml
- resources/chris-store-db.yaml
- resources/rabbitmq.yaml
- resources/swift.yaml
- resources/pfcon.yaml
- resources/pman.yaml
