apiVersion: v1
kind: Service
metadata:
  name: chris-store
  labels:
    name: chris-store
spec:
  type: NodePort
  ports:
  - port: 8010
    targetPort: 8010
    nodePort: 30010
  selector:
    name: chris-store

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-store
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chris-store
  template:
    metadata:
      labels:
        name: chris-store
    spec:
      containers:
      - name: chris-store
        image: fnndsc/chris_store:latest
        ports:
        - containerPort: 8010
        envFrom:
        - configMapRef:
            name: cube-config
        - secretRef:
            name: cube-secrets
