apiVersion: v1
kind: Service
metadata:
  name: chris
  labels:
    name: chris
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
  selector:
    name: chris

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chris
  template:
    metadata:
      labels:
        name: chris
    spec:
      containers:
      - name: chris
        image: fnndsc/chris:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: chris-config
