apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    name: worker
spec:
  type: NodePort
  ports:
  - port: 6900
    targetPort: 6900
    nodePort: 30900
  selector:
    name: worker

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - name: worker
        image: fnndsc/chris
        ports:
        - containerPort: 6900
        command: ["celery"]
        args: ["-A", "core", "worker", "-c", "1", "-l", "DEBUG", "-Q", "main"]
        envFrom:
        - configMapRef:
            name: chris-config
