apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chrisdb
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      volume: chrisdb
