apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: queuedb
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      volume: queuedb
