apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storedb
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 40Gi
  selector:
    matchLabels:
      volume: storedb
