apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swiftdb
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      volume: swiftdb
