apiVersion: v1
kind: Service
metadata:
  name: chris-db
  labels:
    name: chris-db
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30307
  selector:
    name: chris-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chris-db
  template:
    metadata:
      labels:
        name: chris-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: cube-config
        - secretRef:
            name: cube-secrets
