apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    name: queue
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    nodePort: 30672
    name: service-port
  - port: 15672
    targetPort: 15672
    nodePort: 31672
    name: management-port
  selector:
    name: queue

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: queue
  template:
    metadata:
      labels:
        name: queue
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        ports:
        - containerPort: 5672
        - containerPort: 15672
