apiVersion: v1
kind: Service
metadata:
  name: swift
  labels:
    name: swift
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    name: swift

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift
spec:
  replicas: 1
  selector:
    matchLabels:
      name: swift
  template:
    metadata:
      labels:
        name: swift
    spec:
      containers:
      - name: swift
        image: fnndsc/docker-swift-onlyone:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: cube-secrets
